<?php declare(strict_types=1);

namespace GraphQlTools\Test\Unit\Definition;

use Closure;
use GraphQL\Type\Definition\Type;
use GraphQlTools\Contract\TypeRegistry;
use GraphQlTools\Definition\Field\Field;
use GraphQlTools\Definition\GraphQlType;
use GraphQlTools\Helper\Registry\AllVisibleSchemaRule;
use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;
use Prophecy\Prophecy\ObjectProphecy;

class GraphQlTypeTest extends TestCase
{
    use ProphecyTrait;
    private ObjectProphecy|TypeRegistry $registry;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->registry = $this->prophesize(TypeRegistry::class);
    }

    private function instance(Closure $fields, array $interfaces = []): GraphQlType {
        return new class ($fields, $interfaces) extends GraphQlType {
            public function __construct(private readonly Closure $fields, private readonly array $interfaces)
            {
            }

            protected function fields(TypeRegistry $registry): array
            {
                return ($this->fields)($registry);
            }

            protected function interfaces(): array
            {
                return $this->interfaces;
            }

            protected function description(): string
            {
                return 'some description';
            }

            public function getName(): string
            {
                return 'Name';
            }
        };
    }

    public function testToDefinition()
    {
        $definition = $this->instance(fn(TypeRegistry $registry) => [
            Field::withName('id')
                ->ofType(Type::id()),
            Field::withName('lazy')
                ->ofType(Type::id()),
        ])->toDefinition($this->registry->reveal(), new AllVisibleSchemaRule());

        $definition->assertValid();
        self::assertTrue(true);
    }

    public function testTypeName()
    {
        self::assertEquals(
            'Name', $this->instance(fn() => [])->getName()
        );
    }
}
