<?php
# Generated Namespace Prefix
namespace GraphQlTools\Protobuf;

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TypeStat</code>
 */
class TypeStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     */
    private $per_field_stat;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $per_field_stat
     *           Key is (eg) "email" for User.email:String!
     * }
     */
    public function __construct($data = NULL) {
        \GraphQlTools\Protobuf\GPBMetadata\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPerFieldStat()
    {
        return $this->per_field_stat;
    }

    /**
     * Key is (eg) "email" for User.email:String!
     *
     * Generated from protobuf field <code>map<string, .FieldStat> per_field_stat = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPerFieldStat($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \GraphQlTools\Protobuf\FieldStat::class);
        $this->per_field_stat = $arr;

        return $this;
    }

}

