name: Tests


on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'feature/**'


jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Use php 8
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Cache composer dependencies
        id: composer_cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        if: steps.composer_cache.outputs.cache-hit != 'true'
        run: composer install --optimize-autoloader

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests --colors=always
